# Generated by Django 5.0.3 on 2024-04-07 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GuardianGear', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Hours',
            new_name='Hour',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='id',
        ),
        migrations.AddField(
            model_name='appointment',
            name='Appointment_id',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
