# Generated by Django 5.0.3 on 2024-04-07 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GuardianGear', '0003_rename_hour_hours'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='Appointment_id',
        ),
        migrations.AddField(
            model_name='appointment',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
